-- Add migration script here
CREATE TABLE IF NOT EXISTS wallets (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    balance DECIMAL(15, 2) DEFAULT 0,
    coin DECIMAL(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);