-- Add migration script here
CREATE TABLE user_achievements (
    id SERIAL PRIMARY KEY NOT NULL,
    achievement_id INTEGER NOT NULL REFERENCES achievements(id) ON DELETE SET NULL ON UPDATE SET NULL,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL ON UPDATE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);